@url = http://localhost:4510

### ADD SINGLE APPOINTMENT
POST {{url}}/
Content-Type: application/json

{
    "date": "2021-12-12",
    "dayOfWeek": "Monday",
    "appointments":  
        {
        "startTime": 10,
        "endTime": 11,
        "title": "Meeting with John Doe",
        "description": "Discussing the new project"
        }
    
}
