@url = http://localhost:4510

### ADD SINGLE APPOINTMENT
POST {{url}}/
Content-Type: application/json

{
    "date": "2021-12-12",
    "dayOfWeek": "Monday",
    "appointments":  
        {
        "startTime": 10,
        "endTime": 11,
        "title": "Meeting with John Doe",
        "description": "Discussing the new project"
        }
    
}

### GET SINGLE APPOINTMENT
GET {{url}}/65d359317ff6141118d1c430

{
    "appointments": 
    {
        "startTime": 14,
        "endTime": 20,
    }
}

### POST SINGLE TAB
POST {{url}}/
Content-Type: application/json

