@url = http://localhost:4510

### ADD SINGLE APPOINTMENT
POST {{url}}/appointments
Content-Type: application/json

{
    "date": "2021-12-12",
    "dayOfWeek": "Monday",
    "appointments": [ 
        {
        "startTime": "10:00",
        "endTime": "11:00",
        "title": "Meeting with John Doe",
        "description": "Discussing the new project",
        }
    ]
}